version: '3'
services:
  ngrinder-controller:
    image: ngrinder/controller:3.4
    container_name: ngrinder-controller
    ports:
      - "80:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./ngrinder/controller:/opt/ngrinder-controller

  ngrinder-agent:
    container_name: ngrinder-agent-1
    image: ngrinder/agent:3.4
    command: ["ngrinder-controller:80"]

  mysql:
    container_name: sample-mysql
    image: mysql:5.7
    ports:
      - "33306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: simple_board
      MYSQL_ROOT_PASSWORD: password
